# Generated by Django 4.2.7 on 2023-12-14 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='model_yaer',
            new_name='model_year',
        ),
    ]
